before_script:
  - psql -c 'create database UberStatus_test;' -U postgres

language: ruby
rvm:
 - "2.2.1"
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
script: bundle exec rake db:create